"""Add public_url to MediaFile

Revision ID: 0e8c5008fd4f
Revises: f044bceea6f4
Create Date: 2024-10-04 00:36:48.747285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8c5008fd4f'
down_revision = 'f044bceea6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_file', schema=None) as batch_op:
        batch_op.drop_column('public_url')

    # ### end Alembic commands ###
